#!/bin/bash
set -x
set -e
cd ~/permanet/pydbus
rm -r build || $TRUE
#CFLAGS='-Wall -O0 -g'
#export CFLAGS
PYTHONPATH=~/pdev
export PYTHONPATH
#CFLAGS='-Wall -O0 -g' python3.4 setup.py build
python3.4 setup.py build
python3.4 setup.py develop --install-dir ~/pdev

python3.6 setup.py build
python3.6 setup.py develop --install-dir ~/pdev
