#!/bin/bash
set -x
set -e
cd ~/permanet/pydbus
rm -r build || $TRUE
#CFLAGS='-Wall -O0 -g'
#export CFLAGS
PYTHONPATH=~/pdev
export PYTHONPATH
python3 setup.py build
python3 setup.py develop --install-dir ~/pdev

